# refers to `ansible` st2 integration pack:
# https://github.com/StackStorm/st2contrib/tree/master/packs/ansible
---
name: "chatops.ansible_playbook"
action_ref: "ansible.playbook"
description: "Run ansible-playbook command on local machine"
formats:
  - "ansible.playbook {{playbook}}"
